build:
  version: "2.0"

paymentservice:
  message: "E-Commerce-App payment service test stage APIs"
  contactDetails:
    name: "Mahmut Ali Şahinkaya - Developer"
    email: "mahmutsahinkaya@gmail.com"
    linkedin: "https://www.linkedin.com/in/mahmutalisahinkaya/"

